name: Trivy Scheduled Scan

on:
  schedule:
    - cron: '30 * * * *' # Report on Mondays.

jobs:
  # This job should match what's found in trivy-pr-scan.yaml.
  scan_default_branch:
    permissions:
      # for github/codeql-action/upload-sarif to upload SARIF results
      security-events: write 

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Upload actionable results to the GitHub Security tab.
      # Pull request checks fail according to repository settings.
      # - https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
      # - https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning
      - name: Report actionable vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-default-branch-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-default-branch-results.sarif'

  scan_REL_4_7:
    permissions:
      # for github/codeql-action/upload-sarif to upload SARIF results
      security-events: write 

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'REL_4_7'

      - name: Report actionable vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-4-7-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-4-7-results.sarif'
